### PR TITLE
Semar/linked group

### PR DESCRIPTION
**Pull request by semaraugusto**
## Description
Adds `packages/group/src/linkedGroup.ts`. A typescript interface to deal with multi-chain groups

## Related Issue
Closes https://github.com/webb-tools/semaphore-anchor/issues/4

## Does this introduce a breaking change?

-   [x] Yes
-   [ ] No

Should change from Group to LinkedGroup in usage. Note that the interface for Group and LinkedGroup is different.

### CODE REVIEW

**Comment by semaraugusto** [comment]
Also integrates usage of `pacakges/semaphore/src/Semaphore.ts` into cross-chain tests and Semaphore unit-tests. Decided against  updating SemaphoreVoting.ts and SemaphoreWhistleblowing to use `Semaphore.ts` since they'll have their own typescript interfaces and making this integration wouldn't add much to the table

https://github.com/webb-tools/semaphore-anchor/issues/3

**Comment by semaraugusto** [comment]
Closes https://github.com/webb-tools/semaphore-anchor/issues/12

**Comment by semaraugusto** [comment]
Closes https://github.com/webb-tools/semaphore-anchor/issues/13

**Review by drewstone — APPROVED** [review]
LG

**Pull request merged**
